version: "3.9"
services:
  redis:
    image: docker.io/library/redis:7
    container_name: microblogging_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      microblogging-net:
        aliases:
          - redis

  backend:
    container_name: microblogging_backend
    build:
      context: .
      dockerfile: Microblogging.Api/Dockerfile
    image: microblogging_backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
    volumes:
      - ./Microblogging.Api:/backend
    networks:
      microblogging-net:
        aliases:
          - backend
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    container_name: microblogging_frontend
    build:
      context: ./Microblogging.Web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      microblogging-net:
        aliases:
          - frontend
    depends_on:
      - backend
    restart: unless-stopped

networks:
  microblogging-net:
    driver: bridge
